apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: observability
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 51.2.0
    chart: kube-prometheus-stack
    helm:
      values: |
        grafana:
          grafana.ini:
            auth.generic_oauth:
              enabled: true
              name: "Company SSO"
              client_id: "grafana"
              # NOTE: In a true prod environment, use External Secrets to mount this securely!
              client_secret: "keycloak-secret" 
              auth_url: "https://keycloak.corp.internal.com/realms/internal/protocol/openid-connect/auth"
              token_url: "https://keycloak.corp.internal.com/realms/internal/protocol/openid-connect/token"
              api_url: "https://keycloak.corp.internal.com/realms/internal/protocol/openid-connect/userinfo"
              role_attribute_path: "contains(groups[*], 'Dev_Team_Alpha') && 'Editor' || 'Viewer'"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 