apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  destination: { server: 'https://kubernetes.default.svc', namespace: observability }
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 5.41.5
    chart: loki
    helm:
      values: |
        loki: { auth_enabled: true }
  syncPolicy: { automated: { prune: true, selfHeal: true } }