apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-cluster-secret-store
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  source:
    repoURL: 'https://github.com/YOUR_ORG/gitops-repo.git'
    targetRevision: HEAD
    path: cluster-resources # Store this YAML in a generic folder in your repo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true