apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  source:
    repoURL: 'https://charts.external-secrets.io'
    targetRevision: 0.9.9
    chart: external-secrets
    helm:
      values: |
        installCRDs: true
        serviceAccount:
          create: true
          name: "external-secrets-sa"
          annotations:
            # THIS IS THE MAGIC LINK:
            # It tells the Kubernetes pod to assume the AWS IAM Role we just built.
            eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/eks-external-secrets-operator-role"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true