apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: security
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 24.0.0
    chart: keycloak
    helm:
      values: |
        auth:
          adminUser: admin
        # Automatically configure Keycloak to read from AWS Managed AD
        extraEnvVars:
          - name: KEYCLOAK_EXTRA_ARGS
            value: "--features=scripts"
        # In a real setup, you use Keycloak's REST API or a custom init script here 
        # to automatically configure the LDAP User Federation to your AWS AD IP address.
  syncPolicy:
    automated:
      prune: true